// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC11I9q6niCxE73B1vYIJ2XknzhkdDo6s4',
    appId: '1:1078788985612:web:15484f6de2a20f60e6af29',
    messagingSenderId: '1078788985612',
    projectId: 'vslast-premium',
    authDomain: 'vslast-premium.firebaseapp.com',
    storageBucket: 'vslast-premium.firebasestorage.app',
    measurementId: 'G-8653ZX27G4',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJhCtQMaxiMZtPFBkTjTziyejSDgPDNfA',
    appId: '1:1078788985612:ios:8dffcf13a15f9df3e6af29',
    messagingSenderId: '1078788985612',
    projectId: 'vslast-premium',
    storageBucket: 'vslast-premium.firebasestorage.app',
    iosBundleId: 'com.example.vslastPremium',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDebGsc27s7PXd_ICR6HCer93Ajv0hem8g',
    appId: '1:1078788985612:android:2351617d8275453ae6af29',
    messagingSenderId: '1078788985612',
    projectId: 'vslast-premium',
    storageBucket: 'vslast-premium.firebasestorage.app',
  );
}
